echo ""
echo "- update make_jar_zip_release.sh with new version number"
echo ""
echo "- update configure.ac with the new version number"
echo ""
echo "- update LATEST file with the new version number"
echo ""
echo "- update NEWS file in case of release status changed (e.g: BETA to RC...)"
echo ""
echo "- update README file for the changelog"
echo ""
echo "- (update version number inside sudokuki.sh)"
echo ""
echo "- COMMIT the above changes with a notice such as follows:"
echo "Updated control files for new release X"
echo ""
echo "- Do a fresh checkout somewhere else, for example:"
echo "svn co https://sudokuki.svn.sourceforge.net/svnroot/sudokuki/trunk RELEASE"
echo ""
echo "- Remove the .svn directories from this 'RELEASE' copy"
echo "  From there, build the release package:"
echo "cd RELEASE/sudokuki && find . -name ".svn" -exec rm -rf {} \; ; ./autogen.sh && ./configure && make update-po && make dist && make && ./make_jar_zip_release.sh"
echo ""
echo "- Upload LATEST, NEWS, README, and the packages on Sourceforge:"
echo "https://sourceforge.net/projects/sudokuki/files/sudokuki/1.1/Beta"
echo ""
echo "- Test the package:"
echo "  . test the Check-Update feature"
echo "  . other sanity tests"
echo ""
