/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_jankenpoi_sudokuki_generator_suexg_SuexgProxy */

#ifndef _Included_net_jankenpoi_sudokuki_generator_suexg_SuexgProxy
#define _Included_net_jankenpoi_sudokuki_generator_suexg_SuexgProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_jankenpoi_sudokuki_generator_suexg_SuexgProxy
 * Method:    generateSuexgGrid
 * Signature: (III[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_net_jankenpoi_sudokuki_generator_suexg_SuexgProxy_generateSuexgGrid
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray, jintArray);

/*
 * Class:     net_jankenpoi_sudokuki_generator_suexg_SuexgProxy
 * Method:    solveCustomGrid
 * Signature: ([I[I)I
 */
JNIEXPORT jint JNICALL Java_net_jankenpoi_sudokuki_generator_suexg_SuexgProxy_solveCustomGrid
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
